### ISSUE TITLE
Conflict: can't use getUpdates method

### ISSUE THREAD

**Issue by momai** [TiraelSedai/ClubDoorman#7]
Привет! Я хочу протестировать бота, но у меня не получается. После указания значений переменных, я получаю ошибку:
```
doorman    | [21:15:53 ERR] ExecuteAsync
doorman    | Telegram.Bot.Exceptions.ApiRequestException: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
doorman    |    at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
doorman    |    at Telegram.Bot.TelegramBotClientExtensions.GetUpdatesAsync(ITelegramBotClient botClient, Nullable`1 offset, Nullable`1 limit, Nullable`1 timeout, IEnumerable`1 allowedUpdates, CancellationToken cancellationToken)
doorman    |    at ClubDoorman.Worker.UpdateLoop(Int32 offset, CancellationToken stoppingToken) in /src/Worker.cs:line 82
doorman    |    at ClubDoorman.Worker.ExecuteAsync(CancellationToken stoppingToken) in /src/Worker.cs:line 68
```

Мой docker-compose.yaml и .env

```
services:
  doorman:
    image: ghcr.io/tiraelsedai/clubdoorman:latest
    container_name: doorman
    environment:
      - TZ=Europe/Moscow
      - DOORMAN_CLUB_SERVICE_TOKEN=${DOORMAN_CLUB_SERVICE_TOKEN}
      - DOORMAN_BOT_API=${DOORMAN_BOT_API}
      - DOORMAN_ADMIN_CHAT=${DOORMAN_ADMIN_CHAT}
      - DOORMAN_BLACKLIST_AUTOBAN_DISABLE=${DOORMAN_BLACKLIST_AUTOBAN_DISABLE}
      - DOORMAN_LOW_CONFIDENCE_HAM_ENABLE=${DOORMAN_LOW_CONFIDENCE_HAM_ENABLE}
    volumes:
      - ./ClubDoorman/data:/app/data
    restart: unless-stopped
```

```
root@web:~/ClubDoorman# cat .env
DOORMAN_CLUB_SERVICE_TOKEN=
DOORMAN_BOT_API=123456
DOORMAN_ADMIN_CHAT=654321
DOORMAN_BLACKLIST_AUTOBAN_DISABLE=1
DOORMAN_LOW_CONFIDENCE_HAM_ENABLE=1
```

Мог бы автор помочь?
